# Generated by Django 3.0.3 on 2020-09-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hymns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=200)),
                ('Elyrics', models.CharField(max_length=2083)),
                ('id2', models.IntegerField()),
                ('Yname', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=20)),
                ('meter', models.CharField(max_length=10)),
                ('Ylyrics', models.CharField(max_length=2083)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
