# Generated by Django 3.0.3 on 2020-09-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hymns',
            new_name='Hymn',
        ),
    ]
