# Generated by Django 3.0.3 on 2020-09-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200904_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hymn',
            name='Elyrics',
            field=models.TextField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='Ylyrics',
            field=models.TextField(max_length=2083),
        ),
    ]
